server {
    listen 80;
    server_name gtm.cbsp.nl;

    access_log /var/log/nginx/gtm.access.log;
    error_log /var/log/nginx/gtm.error.log;

    location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /home/admtadj@cbsp.nl/Documents/GTM/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location /data/ {
        alias /home/admtadj@cbsp.nl/Documents/GTM/data/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }
}
